[build]
  command = "npm run build"

[[redirects]]
  from = "/phrases"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/rick"
  to = "/index.html"
  status = 200
  force = true